### ISSUE TITLE
Performance improvement: only parse files needed by active recipes

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-maven-plugin#185]
Just an idea: parsing POM can be quite slow when you use a number of dependencies, but this parsing is in fact useless if you have no active recipes of Maven category.

**Comment by jkschneider** [comment]
This is a really good point. I'm kind of embarrassed to say we never really thought of it. Shouldn't be a tough fix?

**Comment by murdos** [comment]
Indeed, that was a tough fix! :smile: 
Should the same logic be also applied to the gradle plugin?

**Comment by wetneb** [comment]
Is this fix still working? I am trying to run OpenRewrite on a Java codebase (https://github.com/OpenRefine/OpenRefine), activating only Java recipes, and OpenRewrite still tries to parse a lot of other files.

To reproduce:
```
git clone --depth 1 https://github.com/OpenRefine/OpenRefine
cd OpenRefine
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.activeRecipes=org.openrewrite.java.RemoveUnusedImports
```

Then, observe that the logs contain the following lines:
```
[WARNING] There were problems parsing some source files, run with --errors to see full stack traces
[WARNING] There were problems parsing .github/workflows/label_transfer/script.py
[INFO] Project [OpenRefine - main] Parsing source files
[INFO] Parsing as quark /tmp/OpenRefine/main/tests/data/ozone_8hr_dmax.csv as its size 14Mb exceeds size threshold 10Mb
```

Because the active recipe is a Java recipe, I would not expect the plugin to attempt Python or CSV files.

Alternatively it would be convenient if one could restrict the plugin to a particular list of includes (but I did not find a counterpart to `<exclusions/>` in the config).

**Comment by timtebeek** [comment]
Some context also provided in this follow up issue:
- https://github.com/openrewrite/rewrite-maven-plugin/issues/643#issuecomment-1768639952
