### ISSUE TITLE
Run plugin only for specific files

### ISSUE THREAD

**Issue by brunodutr** [openrewrite/rewrite-maven-plugin#398]
I want to run rewrite-maven-plugin only on specific files, for example when review one pull request automatically look for files that changed and execute.

Now i able to execute this pattern with checkstyle using `checkstyle.includes` param.

**Comment by pway99** [comment]
Hi @brunodutr, 

per your question on running the rewrite-maven plugin on specific files:

While it's not possible to only include specific files, the maven-plugin can be [configured](https://docs.openrewrite.org/reference/rewrite-maven-plugin#plugin-configuration) with a set of exclusions defined by [PathMatcher](https://docs.oracle.com/javase/8/docs/api/java/nio/file/PathMatcher.html)s

**Comment by tkvangorder** [comment]
To follow on from Pat's comment, it is possible to exclude resource files (yaml, XML, properties, plain text, etc) from being processed by the maven plugin, however, there is no way to exclude *.java files because we are also embedding type information into the ASTs that are used by the recipe. If we exclude java files, the type information would potentially be incomplete.
