### ISSUE TITLE
Provide rewrite as an extension instead of or in addition to a plugin

### ISSUE THREAD

**Issue by cproinger** [openrewrite/rewrite-maven-plugin#405]
i habe a multi-module maven project where the root is not the parent the submodules. that way i have to define the rewrite-plugin in all parent poms. I'm no expert on this, but wouldn't it make more sense to provide rewrite as an extension instead/in-addition-to a plugin?

**Comment by tkvangorder** [comment]
Thank you for the suggestion, I have added this to our backlog for discovery.

**Comment by timtebeek** [comment]
Since this issue was opened we've updated the docs to include instructions for running OpenRewrite without adding anything to the pom.xml file. See for instance: https://docs.openrewrite.org/recipes/java/migrate/upgradepluginsforjava21
```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.migrate.UpgradePluginsForJava21 -Drewrite.exportDatatables=true
```
There had been some issues with multi module projects previously, but those have also been resolved:
- https://github.com/openrewrite/rewrite-maven-plugin/issues/475

With that I think there's less of a need to work out whether we can make the plugin work as an extension, as we try to limit the number of ways folks may use the project, as we'd then have to document, maintain and support those options going forward.
