### ISSUE TITLE
Have default excludes for known binary file types or disable maven resource folder parsing

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-maven-plugin#671]
## What problem are you trying to solve?
Typical Maven projects contain resource folders, and these are part of the classpath, therefore they are currently scanned. Many of those files will not be handled by any recipe, therefore they should be excluded by default. Otherwise the log contains lots of lines about quarks parsing for included libraries, native executables, images etc. This is especially notable when setting the size threshold to 1 MB.

## Describe the solution you'd like
Default filters to contain *.jar, *.exe, *.png, *.gif, *.jpeg etc. 

## Have you considered any alternatives or workarounds?
Alternatively the resource folder could be ignored completely. In my naive assumption the parsing of the actual sources in the source folders should not be affected by that removal. However, someone with real insight into how rewrite works would need to assess that.

## Additional context

I have no idea how the core knows about file types that may or may not be handled by recipes in (custom) rewrite modules. If someone suddenly provided a PNG recipe (imagine a "remove geo tags from image" recipe), this would of course conflict with such default excludes.

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

If it's just about default excludes, that might be possible.

**Comment by timtebeek** [comment]
That helps to know, thanks! So as a bit of context; the Quark parser merely keeps track of the _existence_ of the file, not anything about any content related to it, [as seen here](https://github.com/openrewrite/rewrite/blob/6e19522071f9221f462f6c567fed47ee8ef1e2df/rewrite-core/src/main/java/org/openrewrite/quark/QuarkParser.java#L108-L117). We write a bit [more about that in the docs](https://docs.openrewrite.org/concepts-explanations/quarks).

> A Quark in OpenRewrite serves as a representation of a file that cannot be parsed, either due to its large size or because it is a type we don't have a parser for (such as images or HTML files). Instead of disregarding such files, we capture their path and relevant metadata (but not the contents of these files). This allows you to move or delete these files in recipes.
If you are running a recipe that is not specifically looking for Quarks, you should never see a Quark.

The reason I asked whether the files were in `src/*/resources` or not is because we also separately pick up files outside of resource folders, to for instance read your Maven wrapper files such that they can be updated. This again would not read the contents of anything picked up as Quark.
https://github.com/openrewrite/rewrite-maven-plugin/blob/9a9428fbd211b79cebdec18a68b830e16434ade3/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L202-L213

Right now we print the following message when a file exceeds the file size limit:
https://github.com/openrewrite/rewrite-maven-plugin/blob/28bd2baae54c42de51e16ab3ddddd10fd2406fb8/src/main/java/org/openrewrite/maven/ResourceParser.java#L121-L122

Perhaps it would be clearer to print `Not parsing quark ...`, just to make clear there's no parsing of the contents, but that the files _were_ found when going through the project. We find it helpful to list which files were not parsed, because that's a common source of changes-not-applied, such that it aids debugging.

 So then for your case: I don't think the Quark handling (or additional exclusions to that aim) would have any meaningful effect on the run duration, as we're merely storing a reference to the filename with some properties. Perhaps you'd want to explore using the CLI to reuse LSTs in an effort to speed up repeated runs against the same model?
