### ISSUE TITLE
Automate publishing of the plugin to maven central

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-maven-plugin#79]
Currently, all projects other than the `rewrite-maven-plugin` can be published via an automated ci/cd step. However, this project uses maven and GitHub actions and does not have the ability to automatically publish to maven central. 

This article provides a good overview of how this can be accomplished: 

https://dzone.com/articles/how-to-publish-artifacts-to-maven-central

**Comment by aegershman** [comment]
No guarantees this link will exist as a repo in the future, but, testing this out over in a personal org/repo to not pollute publishes (https://github.com/slugstack/maven-release-example/actions?query=workflow%3Arelease)

Notes for reference:

- http://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html
- https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven
- for scm urls, https://maven.apache.org/scm/git.html -- keep in mind that `https` scm prefixes will play nicely with using github tokens for committing and pushing back, whereas most manual flows are expecting git/ssh for using people's stored ssh keys

**Comment by aegershman** [comment]
used a throwaway repo for messy testing (https://github.com/slugstack/maven-release-example). Will have a PR for this squared up soon

**Comment by aegershman** [comment]
Just as an update, I'm generally mistrustful of processes like this unless demonstrated and tested all the way through, so I'm testing this out against a (personal) maven central repo to test out the full deployment process before committing: https://github.com/slugstack/rewrite-definitions/runs/1744643853?check_suite_focus=true 

It's been worth having it barf up once or twice mid-release to see what to do from the perspective of "the release info has already been updated in git, but it's not reflected on external sources--now what?". Still finishing this up.

**Comment by aegershman** [comment]
It's a little annoying that the release plugin commits with the 'new' version, _then_ pushes those to source, _then_ attempts pushing to repos after that, all in one go. It's kind of annoying that a rollback also involves a commit forward (because it required a commit in the first place). In reality what's really wanted is: "`tag` this commit with a version. then, take source of whatever is at that tagged version and distribute it. track where it was distributed to and if it was successful. if distributing it fails, mark it as failed so we can try again later. if it succeeds, mark that it's been successfully deployed." ... I suppose solving this in the general case is a bit more involved than what we want to do here. It's just an annoying category of problem altogether. I'll poke more to get it simplified. Just making notes here.

**Comment by aegershman** [comment]
Noting to self: hang on, taking a step back here-- the way all the other `rewrite` repos work is that basically when you want to “publish a release”, someone manually does `git tag x.y.z` on a commit and then `git push origin --tags` to remote, and circle-ci will treat that as a release target, right?

in contrast, for repos like `rewrite` itself or `rewrite-checkstyle`, etc., we don’t hardcode the version from within the `build.gradle.kts` or anything, like we do with a `pom.xml`. With the gradle-release plugin + circle-ci, someone wanting to release does a `git tag` first, and doing a deployment ‘release’ is handled by circleci, as shown here, right? https://github.com/openrewrite/rewrite/blob/7d56ebe903b398e7fe33c1e980e140779fe19aac/.circleci/config.yml#L102

Why I’m asking is b/c, it seems like there’s an overall divergence for this one repo. If you tag the commit you want for a release first, and then have circle CI do all the ansillary releasing, it seems like it’d be way easier to do a “re-run deploy” in the event the deployment fails.
